{
 "title": "Tower Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tower CPU Usage",
   "type": "graph",
   "description": "Takes the Idle Time and substracts it from 100. So CPU includes both system and user time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu.usage_idle",
       "id": "1",
       "inlineScript": "100 - _value",
       "meta": {},
       "settings": { "script": { "inline": "100 - _value" } },
       "type": "avg"
      }
     ],
     "query": "tag.node_type:tower",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tower Node Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem.free",
       "id": "1",
       "inlineScript": "_value/100000",
       "meta": {},
       "settings": { "script": { "inline": "_value/100000" } },
       "type": "avg"
      }
     ],
     "query": "tag.node_type:tower",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Free Disk Space - Tower Node",
   "type": "graph",
   "description": "Shows the Output of Free memory per filesystem.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.path.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "disk.free",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag.node_type:tower NOT tag.path:\"/boot\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Capacity Status - Tower Group",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tower_system_capacity.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tower_network_partitions.length",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Capacity / Host",
   "type": "graph",
   "description": "Show System Capacity by host",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tower_system_capacity.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag.node_type:tower",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Partitioned Cluster Details",
   "type": "table",
   "description": "For each Server it shows the list of hosts that are have partitions.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "measurement_name:tower_network_partitions AND tower_network_partitions.length: >0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host License Usage",
   "type": "singlestat",
   "description": "List the percent of licenses used. If it gets to 90% be worried.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "tower_inventory_count.percent_left",
       "id": "1",
       "inlineScript": "100 - _value",
       "meta": {},
       "settings": { "script": { "inline": "100 - _value" } },
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Posgres CPU Usage",
   "type": "graph",
   "description": "Takes the Idle Time and substracts it from 100. So CPU includes both system and user time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpu.usage_idle",
       "id": "1",
       "inlineScript": "100 - _value",
       "meta": {},
       "settings": { "script": { "inline": "100 - _value" } },
       "type": "avg"
      }
     ],
     "query": "tag.node_type:database",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Postgres Node Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "mem.free",
       "id": "1",
       "inlineScript": "_value/100000",
       "meta": {},
       "settings": { "script": { "inline": "_value/100000" } },
       "type": "avg"
      }
     ],
     "query": "tag.node_type:database",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Postgres DB Size vs Total Disk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Tower Database Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "postgresql.pg_database_size",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag.node_type:database",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total Disk Size",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "disk.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag.node_type:database",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}