elastic_metrics_version: 6.2.4
telegraf_version: 1.6.2-1
telegraf_user: admin
telegraf_passwd: tower

# Rabbitmq mgmt username and password. Default to guest:guest
rabbitmq_mgmt_user: guest
rabbitmq_mgmt_user_password: guest

