---
- name: copy telegraf rpm to tmp directory
  copy:
    src: "{{ telegraf_rpm }}"
    dest: "/tmp/{{telegraf_rpm }}"

- name: install telegraf rpm
  yum:
    name: "/tmp/{{telegraf_rpm }}"


- name: copy telegraf scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{item}}"
    mode: 0500
    owner: telegraf
    group: root
  with_items: "{{ telegraf_exec_scripts }}"
  notify:
    - restart telegraf
  when: "'tower' in group_names"

- name: configure telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    backup: yes
    mode: 0400
    owner: telegraf
    group: root
  notify:
    - restart telegraf
